# vim: set syntax=python:

def build(bld):
    t = bld.program(
        source = 'maincte.c',
        target = 'wf3cte.e',
        includes = ['.'],
        use = ['calwf3', 'imphttab', 'wf3cte-fast'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin'
        )
