# vim: set syntax=python:

def build(bld):
    t = bld.stlib(
        source = [
            'cte_dobias.c',
            'wf3cte.c'
            ],
        target = 'wf3cte-fast',
        includes = ['.', '../../../../ctegen2/'],
        use = ['calwf3', 'imphttab', 'ctegen2'] + bld.env.LOCAL_LIBS,
        lib = bld.env.EXTERNAL_LIBS,
        libpath = bld.env.LIBPATH,
        install_path = '${PREFIX}/bin'
        )
