# vim: set syntax=python:

def build(bld):
    t = bld.stlib(
        source = [
            'ctegen2.h'
            'ctegen2.c',
            ],
        target = 'ctegen2',
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib'
        )
