# vim: set syntax=python:

def build(bld):
    t = bld.stlib(
        source = [
            'ctegen2.c'
            ],
        target = 'ctegen2',
        includes = ['.',
                    '../pkg/acs/calacs/acscte/',
                    '../pkg/acs/calacs/include/',
                    '../include/'
                    ],
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib'
        )
