# vim: set syntax=python:

def build(bld):
    t = bld.stlib(
        source = [
            'ctegen2.c'
            ],
        target = 'ctegen2',
        includes = ['.',
                    '../pkg/wfc3/calwf3/wf3cte',
                    '../pkg/wfc3/calwf3/include/',
                    '],
        install_path = bld.env.INSTALL_LIB and '${PREFIX}/lib'
        )
